import pytest
from unittest.mock import patch, MagicMock

from backend.agents.research_agent import ResearchAgent


@pytest.fixture
def agent():
    return ResearchAgent()


def test_analyse_product_valid_json(agent):
    fake_response = """
    {
        "product_summary": "Good product.",
        "usps": ["Fast", "Cheap"],
        "target_audience": ["Students"],
        "competitor_comparision": "Better than others."
    }
    """

    with patch(
        "backend.agents.research_agent.invoke",
        return_value=fake_response
        ) as mock_invoke, \
            patch("backend.agents.research_agent.add_document") as mock_add:

        result = agent.analyse_product("A", "B")

        assert result["product_summary"] == "Good product."
        assert result["usps"] == ["Fast", "Cheap"]
        assert result["target_audience"] == ["Students"]

        mock_invoke.assert_called_once()
        mock_add.assert_called_once()


def test_analyse_product_invalid_json(agent):
    with patch("backend.agents.research_agent.invoke", return_value="NOT_JSON"):

        result = agent.analyse_product("X", "Y")

        assert result["error"] == "Invalid JSON from model."
        assert result["usps"] == []
        assert result["target_audience"] == []


def test_analyse_product_no_response(agent):
    with patch("backend.agents.research_agent.invoke", return_value=None):

        result = agent.analyse_product("X", "Y")

        assert result["error"] == "No response generated by Agent"
        assert result["usps"] == []
        assert result["target_audience"] == []
