import json
import logging

from llm.gemini_pipeline import invoke
from vectorstore.store import add_document

# logging configuration
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class ResearchAgent:
    """
    Agent that performs research and analyses:
    - Product details
    - Competitor details
    - Extracts USPs, target audiences, comparision
    """
    def __init__(self):
        pass

    def analyse_product(
            self, product_text: str, competitor_text: str | None
            ) -> dict:
        """
        Analyses the product text and competitor text
        altogether and provides insights. Then saves these
        to the vector database, and returns structured JSON
        at the end.
        """
        prompt = f"""
        You are a marketing research agent.
        Analyse the following product:
        {product_text}
        Competitor information: {competitor_text if competitor_text else "N/A"}

        Give the results in following JSON format ONLY:
        {{
            "product_summary": "2 Sentences overview",
            "usps": ["USP1", "USP2", "USP3"],
            "target_audience": ["List", "of", "Target", "Audience"],
            "competitor_comparison": "2 Sentences comparision"
        }}
        """
        logger.info(f"Prompt sent to Agent: \n{prompt}")
        response = invoke(prompt)
        if response:
            try:
                result = json.loads(response)
            except json.JSONDecodeError:
                logger.error("JSON Parsing failed. Generating fallback structure.")
                return {
                    "product_summary": "",
                    "usps": [],
                    "target_audience": [],
                    "competitor_comparision": "",
                    "error": "Invalid JSON from model."
                }
            
            # Field normalization
            result.setdefault("product_summary", "")
            result.setdefault("usps", [])
            result.setdefault("target_audience", [])
            result.setdefault("competitor_comparision", "")

            # Cleaning
            if isinstance(result["usps"], str):
                result["usps"] = [result["usps"]]
            
            if isinstance(result["target_audience"], str):
                result["target_audience"] = [result["target_audience"]]

            logger.info("Analysis completed successfully.")
            add_document(
                json.dumps(result),
                metadata={
                    "type": "research",
                    "product_text": product_text,
                    "competititor_text": competitor_text
                    })
            logger.info("Research Analysis stored successfully.")
            
            return result

        return {
            "product_summary": "",
            "usps": [],
            "target_audience": [],
            "competitor_comparision": "",
            "error": "No response generated by Agent"
        }

